# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ba98dec072afb4caee5a835096e4cc001e467462ecb7ac8398030ff96c0aebc6c1e6e4a83184b5377b4d78a17ff0c7012aadaf9f1f86c4ad7737bb68dffe81

test:
  secret_key_base: a6f78e99205637f32510dc96cde2e5e9955fc5c4d4b5aa2a6fff3fdd70fbbdc4cc01eb93e566ccc7e6942e7d0bc9f679ceb22d96c85eff29fa9ed8ab2e5feafb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
